swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /user:
    get:
      operationId: user.read_all
      tags:
        - User
      summary: Read the entire list of user
      description: Read the list of user
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of user to get from user
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering user
          required: false
      responses:
        200:
          description: Successfully read user list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string

    post:
      operationId: user.create
      tags:
        - User
      summary: Create a user and add it to the user list
      description: Create a new user in the user list
      parameters:
        - name: user
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of user to create
              lname:
                type: string
                description: Last name of user to create
      responses:
        201:
          description: Successfully created user in list

  /user/{lname}:
    get:
      operationId: user.read_one
      tags:
        - User
      summary: Read one user from the user list
      description: Read one user from the user list
      parameters:
        - name: lname
          in: path
          description: Last name of the user to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read user from user list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string

    put:
      operationId: user.update
      tags:
        - User
      summary: Update a user in the user list
      description: Update a user in the user list
      parameters:
        - name: lname
          in: path
          description: Last name of the user to update in the list
          type: string
          required: True
        - name: user
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully updated user in user list

    delete:
      operationId: user.delete
      tags:
        - User
      summary: Delete a user from the user list
      description: Delete a user
      parameters:
        - name: lname
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a user from user list

